export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const SIGNUP = 'SIGNUP';
export const SIGNUP_SUCCESS= 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';

export const LOGOUT = 'LOGOUT';

export const GET_NEARBY_USERS = 'GET_NEARBY_USERS';
export const GET_NEARBY_USERS_SUCCESS = 'GET_NEARBY_USERS_SUCCESS';
export const GET_NEARBY_USERS_FAILURE = 'GET_NEARBY_USERS_FAILURE';

export const GET_WATCHLIST_USERS = 'GET_WATCHLIST_USERS';
export const GET_WATCHLIST_USERS_SUCCESS= 'GET_WATCHLIST_USERS_SUCCESS';
export const GET_WATCHLIST_USERS_FAILURE = 'GET_WATCHLIST_USERS_FAILURE';

export const GET_NEW_USERS = 'GET_NEW_USERS';
export const GET_NEW_USERS_SUCCESS = 'GET_NEW_USERS_SUCCESS';
export const GET_NEW_USERS_FAILURE = 'GET_NEW_USERS_FAILURE';

export const SEARCH_USERS = 'SEARCH_USERS';
export const SEARCH_USERS_SUCCESS = 'SEARCH_USERS_SUCCESS';
export const SEARCH_USERS_FAILURE = 'SEARCH_USERS_FAILURE';

export const EMPTY_SEARCH = 'EMPTY_SEARCH'


export const GET_FILTER_USERS = 'GET_FILTER_USERS';
export const GET_FILTER_USERS_SUCCESS= 'GET_FILTER_USERS_SUCCESS';
export const GET_FILTER_USERS_FAILURE= 'GET_FILTER_USERS_FAILURE';

export const USERS_SET_FLAG = 'USERS_SET_FLAG';


export const CHANGE_LOCATION = 'CHANGE_LOCATION';
export const CHANGE_LOCATION_SUCCESS = 'CHANGE_LOCATION_SUCCESS';
export const CHANGE_LOCATION_FAILURE = 'CHANGE_LOCATION_FAILURE';


//Gallery
export const GET_GALLERY = 'GET_GALLERY';
export const GET_GALLERY_SUCCESS = 'GET_GALLERY_SUCCESS';
export const GET_GALLERY_FAILURE = 'GET_GALLERY_FAILURE';

export const DELETE_IMAGE_GALLERY = 'DELETE_GALLERY';
export const DELETE_IMAGE_GALLERY_SUCCESS = 'DELETE_GALLERY_SUCCESS';
export const DELETE_IMAGE_GALLERY_FAILURE = 'DELETE_GALLERY_FAILURE';

export const ADD_IMAGE_GALLERY = 'ADD_GALLERY';
export const ADD_IMAGE_GALLERY_SUCCESS = 'ADD_GALLERY_SUCCESS';
export const ADD_IMAGE_GALLERY_FAILURE = 'ADD_GALLERY_FAILURE';
export const ADD_IMAGE_GALLERY_PROCESS = 'ADD_IMAGE_GALLERY_PROCESS';

//Profile

export const GET_MY_GALLERY = 'GET_MY_GALLERY';
export const GET_MY_GALLERY_SUCCESS = 'GET_MY_GALLERY_SUCCESS';
export const GET_MY_GALLERY_FAILURE = 'GET_MY_GALLERY_FAILURE';

export const LOAD_PROFILE = 'LOAD_PROFILE';
export const LOAD_PROFILE_SUCCESS = 'LOAD_PROFILE_SUCCESS';
export const LOAD_PROFILE_FAILURE = 'LOAD_PROFILE_FAILURE';

export const UPDATE_PROFILE_IMAGE = 'UPDATE_PROFILE_IMAGE';
export const UPDATE_PROFILE_IMAGE_SUCCESS = 'UPDATE_PROFILE_IMAGE_SUCCESS';
export const UPDATE_PROFILE_IMAGE_FAILURE = 'UPDATE_PROFILE_IMAGE_FAILURE';
export const UPDATE_PROFILE_IMAGE_PROCESS = 'UPDATE_PROFILE_IMAGE_PROCESS'

export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_FAILURE = 'UPDATE_PROFILE_FAILURE';

export const UPDATE_EMAIL = 'UPDATE_EMAIL';
export const UPDATE_EMAIL_SUCCESS = 'UPDATE_EMAIL_SUCCESS';
export const UPDATE_EMAIL_FAILURE = 'UPDATE_EMAIL_FAILURE';

export const UPDATE_PASSWORD = 'UPDATE_PASSWORD';
export const UPDATE_PASSWORD_SUCCESS = 'UPDATE_PASSWORD_SUCCESS';
export const UPDATE_PASSWORD_FAILURE = 'UPDATE_PASSWORD_FAILURE';

export const UPDATE_SETTINGS = 'UPDATE_SETTINGS';


//App

export const GET_MODIFIABLES = "GET_MODIFIABLES";
export const GET_MODIFIABLES_SUCCESS = "GET_MODIFIABLES_SUCCESS";
export const GET_MODIFIABLES_FAILURE = "GET_MODIFIABLES_FAILURE";


//Filter
export const ENABLE_FILTER = "ENABLE_FILTER";
export const UPDATE_FILTER = "UPDATE_FILTER";
export const RESET_FILTER = "RESET_FILTER";
