export const GET_NEARBY_USERS = 'GET_NEARBY_USERS';
export const GET_NEARBY_USERS_SUCCESS = 'GET_NEARBY_USERS_SUCCESS';
export const GET_NEARBY_USERS_FAILURE = 'GET_NEARBY_USERS_FAILURE';

export const GET_WATCHLIST_USERS = 'GET_WATCHLIST_USERS';
export const GET_WATCHLIST_USERS_SUCCESS= 'GET_WATCHLIST_USERS_SUCCESS';
export const GET_WATCHLIST_USERS_FAILURE = 'GET_WATCHLIST_USERS_FAILURE';

export const GET_NEW_USERS = 'GET_NEW_USERS';
export const GET_NEW_USERS_SUCCESS = 'GET_NEW_USERS_SUCCESS';
export const GET_NEW_USERS_FAILURE = 'GET_NEW_USERS_FAILURE';

export const SEARCH_USERS = 'SEARCH_USERS';
export const SEARCH_USERS_SUCCESS = 'SEARCH_USERS_SUCCESS';
export const SEARCH_USERS_FAILURE = 'SEARCH_USERS_FAILURE';


export const GET_FILTER_USERS = 'GET_FILTER_USERS';
export const GET_FILTER_USERS_SUCCESS= 'GET_FILTER_USERS_SUCCESS';
export const GET_FILTER_USERS_FAILURE= 'GET_FILTER_USERS_FAILURE';

export const USERS_SET_FLAG = 'USERS_SET_FLAG';

